sudo: false

addons:
  apt:
    packages:
    - libglu1-mesa

language: generic

cache:
  directories:
  - blender

env:
  - BLENDER_VERSION=2.83

install:
  - sh ./tests/ci-prepare.sh

script:
  - ./blender/$BLENDER_VERSION/blender --factory-startup -noaudio -b --python-exit-code 1 --python tests/runner.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
